name: "Exercicio"

on:
  push:
  
jobs:
  print_exercicio_ubuntu:
    name: Exercicio Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Exercicio Ubuntu!
        run: 'date'
        
  print_exercicio_windows:
    name: Exercicio Windows!
    runs-on: windows-latest
    
    steps:
      - name: Exercicio Windows!
        run: 'date'
        
  print_exercicio_macos:
    name: Exercicio MacOs!
    runs-on: macos-latest
    
    steps:
      - name: Exercicio MacOs!
        run: 'date'
        
  print_ultimo_desafio:
    name: Ultimo Desafio!
    runs-on: ubuntu-latest
    
    needs:
      - print_exercicio_ubuntu
      - print_exercicio_windows
      - print_exercicio_macos
    
    steps:
      - name: Ultimo Desafio!
        run: 'date'
        

